### ISSUE TITLE
TypeError: Cannot read property 'content-type' of undefined

### ISSUE THREAD

**Issue by JakeHenshall** [michtio/laravel-mix-criticalcss#2]
Hi,

I'm getting a TypeError: Cannot read property 'content-type' of undefined issue.

TypeError: Cannot read property 'content-type' of undefined
    at temp (/Users/jake/code/test/node_modules/critical/lib/file-helper.js:106:37)
    at requestAsync.then.response (/Users/jake/code/test/node_modules/critical/lib/file-helper.js:193:27)
Canceled due to an error

`   .criticalCss({
    enabled: mix.inProduction(),
    urls: [
        { url: 'http://test.local/', template: 'public/css/index_critical.min.css' },
    ],
    options: {
        minify: true,
    },
    })`

This is also in my Laravel.mix file

`require('laravel-mix-criticalcss');`

Any help would be great.

Thanks, Jake.

**Comment by AdrianKuriata** [comment]
Same problem! I see this error showing after added `enabled: mix.inProduction(),`.

**Comment by JakeHenshall** [comment]
@AdrianKuriata I've just had a thought try adding `type="text/css"` like this `<link rel="stylesheet" type="text/css" href="app.css">` Please let me know if that does anything? I can't test it right now. I will update once i'm home to test.

Thanks, Jake.

**Comment by AdrianKuriata** [comment]
I mistake, sorry. This error showing when you put in terminal `npm run prod`, with `npm run dev` working. I have a problem, after compiling mix files isn't generated.

**Comment by davideprevosto** [comment]
Hi there, I have the same identical issue.

Using `npm run dev` it seems nothing happens (maybe due mix.inProduction() return false of course).
Using `npm run production` I am getting:

`95% emittingTypeError: Cannot read property 'content-type' of undefined`

Any ideas?

Regards

**Comment by davideprevosto** [comment]
@JakeHenshall @AdrianKuriata I think I "solve" the issue. It's about us, I suppose.

This is my configuration:

```
mix
  .sass('assets/styles/main.scss', 'dist/styles/style.css')
  .criticalCss({
    enabled: mix.inProduction(),
    paths: {
      base: 'https://test.local',
      templates: './my-critical-css-folder/'
    },
    urls: [
      { url: '/', template: 'home' },
    ],
    options: {
      minify: true,
    },
  });

```
With this conf, it's working for me. 

PS: template is just called "home" because if you look at source code you'll find:
`const criticalDest = this.config.paths.templates + template.template + '_critical.min.css';`

**Comment by michtio** [comment]
@JakeHenshall @AdrianKuriata could you also share your laravel-mix config file? So I can run some tests and try to determine what is actually going in?

**Comment by AdrianKuriata** [comment]
@michtio It was really a lot of days ago, i can't help you right now.

**Comment by tyssen** [comment]
I'm having this problem at the moment. Should I start a new issue or add more detail to this one?

**Comment by mreduar** [comment]
I found out the issue is about the routes. In my case I had to put the slash on the routes, since the base path was without the slash.

```
    .criticalCss({
        enabled: mix.inProduction(),
        paths: {
            base: 'https://example.dev',
            templates: './resources/critical/',
            suffix: '_critical.min'
        },
        urls: [
            { url: '/requests/', template: 'request' },
            { url: '/genre/', template: 'genre' },
            { url: '/release/', template: 'release' },
            { url: '/label', template: 'label' },
        ],
        options: {
            minify: false,
        },
    });
```

**Comment by ultrono** [comment]
Getting the same error using Laravel Mix 5.0.1 - assume v4 is the latest supported version, hence the error?

**Comment by vanderb** [comment]
> Getting the same error using Laravel Mix 5.0.1 - assume v4 is the latest supported version, hence the error?

I cannot verify this. Just installed laravel-mix 4.1.4 and error still exists.

In my case the error caused by wrong configuration like MrEduar wrote above.

**If that does not help**:

You can simply debug the response of each file processed by this package:

- Open /node_modules/critical/lib/file-helper.js
- Go to line 106 (or search for temp-function)
- Console log the response-param of the function
´console.log(resp)´

Run your script and look in your terminal. Now the response should be logged before error caused. So you can verify if the url and base are valid and accessible.

After that dont forget to undo your changes to the file-helper.js
